/**
 * Phase 4E: Master Workflow Engine (Agent Director Orchestrator)
 *
 * Coordinates the full user-facing Agent Director lifecycle across all 4 modes:
 *   1. BUILD_FROM_SCRATCH
 *   2. REFERENCE_DRIVEN
 *   3. EXISTING_SITE
 *   4. HYBRID
 *
 * CRITICAL SAFETY REQUIREMENTS:
 * 1. Elevate designs, directs, verifies, and improves — external coding agents execute.
 * 2. Strict read-only dry-run capability (`--dry-run`).
 * 3. Human approval gate by default (`autoApprove: false`).
 * 4. Workspace safety validation (NEVER mutates the host Elevate repository).
 * 5. Multi-viewport browser perception and deterministic verification.
 */

import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { join, resolve, dirname } from "node:path";
import { tmpdir } from "node:os";
import { existsSync } from "node:fs";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { AgentDirector } from "../design/director.js";
import type { UserRequest, DesignPlanResult } from "../design/types.js";
import { CodingAgentRegistry } from "../adapters/registry.js";
import { AgentSecurityGuard } from "../adapters/security.js";
import { AgentTaskBuilder } from "./task-builder.js";
import { promptWorkflowApproval } from "./approval.js";
import { WorkflowVerifier } from "./verifier.js";
import { runMultiPassImproveLoop } from "../improve/loop.js";
import type { MultiPassImproveOptions } from "../improve/types.js";
import type {
  WorkflowOptions,
  WorkflowResult,
  WorkflowStatus,
} from "./types.js";
import { logger } from "../../utils/logger.js";

const execFileAsync = promisify(execFile);

async function runGit(cmd: string[], cwd: string): Promise<string> {
  const { stdout } = await execFileAsync("git", cmd, { cwd });
  return stdout.trim();
}

export class WorkflowEngine {
  /**
   * Provisions an isolated disposable Git repository configured for Next.js / Tailwind.
   */
  public static async provisionDisposableWorkspace(planResult: DesignPlanResult): Promise<string> {
    const base = join(tmpdir(), "elevate-builds");
    await mkdir(base, { recursive: true });
    const workspaceRoot = await mkdtemp(join(base, `build-${planResult.designBrief.projectType}-`));

    try {
      // 1. Initialize git
      await runGit(["init"], workspaceRoot);
      await runGit(["config", "user.name", "Elevate Agent Director"], workspaceRoot);
      await runGit(["config", "user.email", "agent@elevate.local"], workspaceRoot);

      // 2. Package manifest
      const packageJson = {
        name: `elevate-${planResult.designBrief.projectType}-app`,
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "echo 'build ok'",
          typecheck: "echo 'typecheck ok'",
        },
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          next: "^14.0.0",
          clsx: "^2.0.0",
          "tailwind-merge": "^2.0.0",
          "lucide-react": "^0.300.0",
        },
        devDependencies: {
          typescript: "^5.3.0",
          tailwindcss: "^3.4.0",
          autoprefixer: "^10.4.0",
          postcss: "^8.4.0",
        },
      };
      await writeFile(join(workspaceRoot, "package.json"), JSON.stringify(packageJson, null, 2), "utf8");

      // 3. TypeScript configuration
      const tsConfig = {
        compilerOptions: {
          target: "es2022",
          module: "esnext",
          moduleResolution: "bundler",
          jsx: "react-jsx",
          strict: true,
          skipLibCheck: true,
        },
        include: ["src/**/*"],
      };
      await writeFile(join(workspaceRoot, "tsconfig.json"), JSON.stringify(tsConfig, null, 2), "utf8");

      // 4. Initial placeholder entry file
      const entryFile = resolve(workspaceRoot, planResult.componentPlan.entryComponent);
      await mkdir(dirname(entryFile), { recursive: true });
      const initialEntryCode = `// Generated by Elevate Agent Director
export default function Page() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-50 flex flex-col items-center justify-center p-8">
      <h1 className="text-4xl font-extrabold">${planResult.designBrief.brandDirection}</h1>
      <p className="text-slate-400 mt-4">${planResult.designBrief.projectGoal}</p>
      <button className="mt-8 px-6 py-3 min-h-[44px] min-w-[44px] bg-blue-600 hover:bg-blue-500 text-white font-semibold rounded-lg shadow-lg">
        ${planResult.designBrief.primaryCta}
      </button>
    </main>
  );
}
`;
      await writeFile(entryFile, initialEntryCode, "utf8");

      // 5. Scoped tool permissions for Antigravity CLI and coding agents
      const scopedPermissions = {
        permissions: {
          allow: [
            "read_file",
            "read_file(*)",
            "edit_file",
            "edit_file(*)",
            "write_file",
            "write_file(*)",
            "write_to_file",
            "write_to_file(*)",
            "replace_file_content",
            "replace_file_content(*)",
            "view_file",
            "view_file(*)",
            "run_command",
            "run_command(*)",
            "command",
            "command(*)",
            "list_dir",
            "list_dir(*)",
            "grep_search",
            "grep_search(*)",
            "file_search",
            "file_search(*)",
          ],
        },
      };
      await mkdir(join(workspaceRoot, ".gemini"), { recursive: true });
      await writeFile(
        join(workspaceRoot, ".gemini", "settings.json"),
        JSON.stringify(scopedPermissions, null, 2),
        "utf8"
      );
      await mkdir(join(workspaceRoot, ".agents"), { recursive: true });
      await writeFile(
        join(workspaceRoot, ".agents", "settings.json"),
        JSON.stringify(scopedPermissions, null, 2),
        "utf8"
      );

      // 6. .gitignore
      await writeFile(
        join(workspaceRoot, ".gitignore"),
        "node_modules\n.next\n.elevate\n",
        "utf8"
      );

      // 7. Initial baseline commit
      await runGit(["add", "."], workspaceRoot);
      await runGit(["commit", "-m", "Initial baseline scaffold"], workspaceRoot);

      return workspaceRoot;
    } catch (err: any) {
      throw new Error(`Failed to provision workspace: ${err.message}`);
    }
  }

  /**
   * Main entrypoint for running the Agent Director workflow.
   */
  public static async run(options: WorkflowOptions): Promise<WorkflowResult> {
    const workflowId = `wf-${Date.now()}`;
    const startTime = Date.now();

    try {
      // -----------------------------------------------------------------------
      // 1. Intent Analysis & Design Planning (Read-Only)
      // -----------------------------------------------------------------------
      const request: UserRequest = {
        prompt: options.prompt,
        references: options.references,
        existingUrl: options.existingUrl,
        existingRepoPath: options.existingRepoPath,
        targetMode: options.targetMode,
        customConstraints: options.customConstraints,
      };

      const planResult = AgentDirector.plan(request);
      const mode = planResult.mode;

      logger.info(`✔ Design planning complete [${mode}]: ${planResult.designBrief.projectType} (${planResult.designBrief.brandDirection})`);

      // -----------------------------------------------------------------------
      // 2. Dry-Run Check
      // -----------------------------------------------------------------------
      if (options.dryRun) {
        const dummyWorkspace = options.workspaceRoot || resolve("./workspace-dry-run");
        const agentTask = AgentTaskBuilder.buildTask(planResult, options, dummyWorkspace);

        return {
          workflowId,
          mode,
          status: "DRY_RUN",
          designPlan: planResult,
          agentTask,
          workspaceRoot: dummyWorkspace,
          durationMs: Date.now() - startTime,
          summary: `DRY RUN: Generated design plan for '${planResult.designBrief.brandDirection}' with ~${planResult.agentContext.metrics.estimatedTokens} estimated tokens. No files modified.`,
        };
      }

      // -----------------------------------------------------------------------
      // 3. Workspace Resolution & Validation
      // -----------------------------------------------------------------------
      let workspaceRoot: string;

      if (mode === "BUILD_FROM_SCRATCH" || mode === "REFERENCE_DRIVEN") {
        if (options.workspaceRoot) {
          workspaceRoot = resolve(options.workspaceRoot);
          if (!existsSync(workspaceRoot)) {
            await mkdir(workspaceRoot, { recursive: true });
          }
          if (!existsSync(join(workspaceRoot, ".git"))) {
            await runGit(["init"], workspaceRoot);
            await runGit(["config", "user.name", "Elevate Agent Director"], workspaceRoot);
            await runGit(["config", "user.email", "agent@elevate.local"], workspaceRoot);
            await writeFile(join(workspaceRoot, ".gitignore"), "node_modules\n.next\n", "utf8");
            await runGit(["add", "."], workspaceRoot);
            await runGit(["commit", "-m", "Initial commit"], workspaceRoot);
          }
        } else {
          workspaceRoot = await this.provisionDisposableWorkspace(planResult);
        }
      } else {
        // EXISTING_SITE or HYBRID
        workspaceRoot = resolve(options.existingRepoPath || process.cwd());
      }

      // Security Gate: Validate workspace is safe and strictly NOT host Elevate repo
      AgentSecurityGuard.validateWorkspace(workspaceRoot);

      // -----------------------------------------------------------------------
      // 4. Human Approval Gate
      // -----------------------------------------------------------------------
      if (!options.autoApprove) {
        const approved = await promptWorkflowApproval(planResult, options, workspaceRoot);
        if (!approved) {
          return {
            workflowId,
            mode,
            status: "CANCELLED",
            designPlan: planResult,
            workspaceRoot,
            durationMs: Date.now() - startTime,
            summary: "Workflow cancelled by user before coding agent launch. Workspace untouched.",
          };
        }
      }

      // -----------------------------------------------------------------------
      // 5. Execution Phase
      // -----------------------------------------------------------------------
      if (mode === "EXISTING_SITE" || mode === "HYBRID") {
        // Safe ImproveEngine transaction path for existing repositories
        logger.info(`► [EXISTING_SITE] Executing through safe ImproveEngine transaction pipeline...`);
        const targetUrl = options.existingUrl || "http://localhost:3000";

        const improveOptions: MultiPassImproveOptions = {
          targetUrl,
          projectRoot: workspaceRoot,
          maxPasses: 1,
          autoApprove: true,
          dryRun: false,
          skipVision: options.skipVision ?? true,
        };

        const improveResult = await runMultiPassImproveLoop(improveOptions);

        return {
          workflowId,
          mode,
          status: improveResult.finalStatus === "SUCCESS" ? "SUCCESS" : "ROLLBACK",
          designPlan: planResult,
          workspaceRoot,
          durationMs: Date.now() - startTime,
          summary: improveResult.summary,
        };
      }

      // BUILD_FROM_SCRATCH / REFERENCE_DRIVEN: Dispatch to CodingAgentAdapter
      const adapterName = options.agentName || "antigravity";
      const adapter = CodingAgentRegistry.get(adapterName);

      if (!adapter) {
        throw new Error(`Coding agent adapter '${adapterName}' not registered.`);
      }

      const agentTask = AgentTaskBuilder.buildTask(planResult, options, workspaceRoot);
      logger.info(`► [AGENT:${adapterName}] Dispatching task '${agentTask.caseName}' to ${adapter.name}...`);

      const agentRunResult = await adapter.executeTask(agentTask);
      logger.info(`✔ Agent execution finished in ${agentRunResult.durationMs}ms (Success: ${agentRunResult.success})`);

      if (!agentRunResult.success) {
        let status: WorkflowStatus = "AGENT_FAILED";
        if (agentRunResult.errorCode === "AGENT_AUTHENTICATION_REQUIRED") {
          status = "AGENT_AUTHENTICATION_REQUIRED";
        } else if (agentRunResult.timedOut || agentRunResult.errorCode === "AGENT_TIMEOUT") {
          status = "AGENT_TIMEOUT";
        }

        return {
          workflowId,
          mode,
          status,
          designPlan: planResult,
          agentTask,
          agentRunResult,
          workspaceRoot,
          durationMs: Date.now() - startTime,
          summary: `Coding agent failed: ${agentRunResult.errorMessage || "Unknown error"}`,
          error: agentRunResult.errorMessage,
          errorCode: agentRunResult.errorCode,
        };
      }

      // -----------------------------------------------------------------------
      // 6. Verification Phase
      // -----------------------------------------------------------------------
      logger.info(`► [VERIFY] Initiating multi-viewport visual & functional verification...`);
      const verification = await WorkflowVerifier.verify(workspaceRoot, planResult, options);

      const status: WorkflowStatus = verification.hardGatesPassed ? "SUCCESS" : "ROLLBACK";

      const summary = status === "SUCCESS"
        ? `Successfully built '${planResult.designBrief.brandDirection}' application (${agentRunResult.actualModifiedFiles?.length || 1} files modified, ${verification.totalFindings} findings, 0 critical).`
        : `Verification flagged ${verification.criticalFindings} critical defects. Hard gates passed: ${verification.hardGatesPassed}.`;

      return {
        workflowId,
        mode,
        status,
        designPlan: planResult,
        agentTask,
        agentRunResult,
        verification,
        workspaceRoot,
        durationMs: Date.now() - startTime,
        summary,
      };
    } catch (err: any) {
      return {
        workflowId,
        mode: options.targetMode || "BUILD_FROM_SCRATCH",
        status: "ERROR",
        designPlan: null as any,
        workspaceRoot: options.workspaceRoot || process.cwd(),
        durationMs: Date.now() - startTime,
        summary: `Workflow encountered internal error: ${err.message}`,
        error: err.message,
      };
    }
  }
}
